Notification toast two
fedimint/fedimint-ui pull request #581
Opened 2024-11-20 01:27 UTC by kleyberthsantos

Issue #496 

### Implementation Summary

**Objective**: Implement a unified notification system using Chakra UI's toast functionality to ensure a consistent user experience and improve code maintainability.

**Key Changes**:

- **NotificationProvider**: Created to centralize and manage notifications (success, error, warning, info) using Chakra UI's `useToast`.

- **Updated Components**:
  - **SetupComplete.tsx**: Added notifications for setup completion.
  - **SendOnchainSuccess.tsx**: Added notifications for successful on-chain transactions.

**Features**:

- Notifications appear in the top-right corner.
- Utilizes existing translations for consistent messaging.
- Consistent notification system across the application.

**Provider Implementation**:
- **Before**: Used `SharedChakraProvider`.
- **Now**: Uses `ChakraProvider` with `NotificationProvider` for full toast functionality.

2024-12-02 19:52 UTC, Kodylow commented
@kleyberthsantos can you run through these coderabbit suggestions before I review?

2024-12-02 20:16 UTC, kleyberthsantos commented
@Kodylow I will review Coderabbit's suggestions and let you know when it is ready. Thanks!

2024-12-04 02:08 UTC, kleyberthsantos commented on apps/router/src/guardian-ui/components/setup/RunDKG.tsx
> +            //showSuccess(t('run-dkg.completed'));
Enable notifications for the DKG process ✅

2024-12-04 02:41 UTC, kleyberthsantos commented on apps/router/src/index.tsx
> +        </AppContextProvider>
move ColorModeScript and Fonts inside NotificationProvider ✅

2024-12-04 03:47 UTC, kleyberthsantos commented on apps/router/src/index.tsx
> +    </ChakraProvider>
This ChakraProvider is essential for notifications to work.

2024-12-04 20:02 UTC, kleyberthsantos commented on apps/router/src/gateway-ui/components/federations/ConnectFederation.tsx
> +        onClose();
Unnecessary success notification ✅

2024-12-04 20:39 UTC, kleyberthsantos commented on apps/router/src/gateway-ui/components/federations/ConnectFederation.tsx
> +        setErrorMsg(errorMessage);
Clear error state before new connection attempt in handleConnectFederation ✅

2024-12-04 21:05 UTC, kleyberthsantos commented on apps/router/src/guardian-ui/setup/FederationSetup.tsx
> +  }, [dispatch, prevProgress, showSuccess, t]);
Remove success notification for back navigation ✅

2024-12-23 22:08 UTC, kleysc commented
I share a sample of the functionality of notifications.

https://github.com/user-attachments/assets/12062868-d96f-487f-ac79-327352dab65f

2024-12-26 19:54 UTC, Kodylow commented
can you remove that package-lock.json otherwise good to go

2024-12-26 19:59 UTC, kleysc commented
> can you remove that package-lock.json otherwise good to go

Yes, already on that

2025-01-13 18:16 UTC, alexlwn123 requested changes
Thanks for the contribution! A couple of comments to address

2025-01-13 18:16 UTC, alexlwn123 commented on apps/router/src/index.tsx
> +      <SharedChakraProvider theme={theme}>
I don't think we want to add an additional ChakraProvider. We should be using the existing `SharedChakraProvider`. 

Is there additional rationale for adding this? Are you running into any issues with the existing provider?

2025-01-13 18:16 UTC, alexlwn123 commented on apps/router/src/home/NotificationProvider.tsx
> +        ...options,
Would it make sense to add these defaults to the Chakra theme? If so, should we reference the `useToast` directly in components instead of adding an additional provider?

ref: https://v2.chakra-ui.com/docs/components/toast/usage#configuring-toast-globally

2025-01-27 20:32 UTC, kleysc commented on apps/router/src/index.tsx
> +      <SharedChakraProvider theme={theme}>
Hi @alexlwn123 👋 
The `SharedChakraProvider` is mainly designed to share the theme and base styles across components, while the root `ChakraProvider` handles specific functionalities like the notification system (toasts).
I suggest keeping both providers for now and creating a separate issue to explore how we could unify them without breaking the notification functionality. Let me know what you think!

2025-01-27 20:32 UTC, kleysc commented on apps/router/src/home/NotificationProvider.tsx
> +        ...options,
For now, it wouldn’t be optimal to move these defaults to the Chakra theme. While it makes sense conceptually, in practice, configuring toasts through the theme causes notifications to appear in the center of the screen instead of the top-right, even when the position is explicitly specified.

2025-01-27 20:50 UTC, alexlwn123 commented on apps/router/src/home/NotificationProvider.tsx
> +        ...options,
Thanks for clarifying! I haven’t seen an issue where configuring toasts globally forces them to the center. Could you share a snippet or repro?

2025-01-27 20:54 UTC, alexlwn123 commented on apps/router/src/index.tsx
> +      <SharedChakraProvider theme={theme}>
Could you please provide more details on the issues you're facing with the existing `SharedChakraProvider`?

2025-01-27 22:05 UTC, kleysc commented on apps/router/src/index.tsx
> +      <SharedChakraProvider theme={theme}>
The issue with the existing `SharedChakraProvider` lies in its current implementation, which doesn’t configure the `toastOptions` required for the notification system.

1. **NotificationProvider Dependency:**
   - The `NotificationProvider` uses the `useToast` hook from Chakra UI, which requires the full Chakra context, including the internal `ToastProvider`.

2. **SharedChakraProvider Limitation:**
   - While the `SharedChakraProvider` extends the `ChakraProvider`, it does not currently pass the `toastOptions` prop, which is necessary to configure notification defaults (e.g., position, duration, etc.).

3. **Resulting Issue:**
   - Due to this limitation, the notifications fail to display entirely, as the `useToast` hook cannot access the required context provided by the `ToastProvider`.

4. **Technical Details:**
   - The `ChakraProvider` natively supports a `toastOptions` prop as part of its `ChakraProviderProps`. However, our current implementation of `SharedChakraProvider` does not utilize this feature, causing the notification system to break.

2025-01-28 11:46 UTC, kleysc commented on apps/router/src/home/NotificationProvider.tsx
> +        ...options,
Here’s a snippet of the configuration when moving the toast settings to theme.tsx:
`packages/ui/src/theme.tsx`

> Toast: {
        defaultProps: {
          duration: 5000,
          isClosable: true,
          position: 'top-right'
        }
}


Here's a screenshot showing how notifications appear in the center and bottom instead of in the top right corner:
![image](https://github.com/user-attachments/assets/cfbb7a74-2713-4a8f-abd0-e129585a65bc)

2025-02-25 15:41 UTC, tsmith123 commented
@alexlwn123 @kleysc Can we get this PR resolved in some way?

2025-02-26 18:32 UTC, alexlwn123 commented
Hey @kleysc, appreciate your efforts on this! After reviewing the changes, I’m going to close this PR, but I’d love to see this implemented a bit differently if you’re up for it.

Here’s what I’d suggest:
 1. Reimplement without adding an extra provider. The wrapper functions don’t seem necessary, and we shouldn’t need an additional Chakra provider.
 2. Double-check dependencies. yarn.lock shouldn’t change unless there are actual modifications to package.json.

2025-02-26 18:32 UTC, closed without merging